### ISSUE TITLE
Usage guide

### ISSUE THREAD

**Issue by AlexsJones** [sxd/cloudnative-pg-addon#1]
After installation, I am not sure what I am supposed to do next. 
Is it possible to have batteries included?

```
❯ kubectl get pods -n cnpg-system
No resources found in cnpg-system namespace.

```

I see the CRD's are available but as a first-time MicroK8s pg user this doesn't get me a database.

Thanks for the contribution!

**Comment by sxd** [comment]
hi @AlexsJones 

I've added a couple of things more like waiting for the deploy and also an example cluster to start, what do you think about it ?
Do you think we should add more?

Thanks!

**Comment by AlexsJones** [comment]
This looks good and I was able to create a cluster with the example.
I suggested a change to call `microk8s kubectl` so that users without kubectl installed can run it as well.

```
cat <<EOF | microk8s kubectl apply -f -
# Example of PostgreSQL cluster
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  storage:
    size: 1Gi
EOF


```
